In [2]:
import pandas as pd

df = pd.read_csv("Sample - Superstore.csv", encoding='latin1')

print(df.shape)
df.head()

(9994, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [4]:
df[['Sales','Profit','Discount','Category','Sub-Category','Region']].head()

      Sales    Profit  Discount         Category Sub-Category Region
0  261.9600   41.9136      0.00        Furniture    Bookcases  South
1  731.9400  219.5820      0.00        Furniture       Chairs  South
2   14.6200    6.8714      0.00  Office Supplies       Labels   West
3  957.5775 -383.0310      0.45        Furniture       Tables  South
4   22.3680    2.5164      0.20  Office Supplies      Storage  South

In [ ]:
# Date column ko date format me convert karo
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Month'] = df['Order Date'].dt.month
df['Year'] = df['Order Date'].dt.year

In [4]:
# Kaunsi category overall profit de rahi hai
# Kaunsi category me loss ho raha hai
df.groupby('Category')[['Sales','Profit']].sum().sort_values(by='Profit', ascending=False)

                       Sales       Profit
Category
Technology       836154.0330  145454.9481
Office Supplies  719047.0320  122490.8008
Furniture        741999.7953   18451.2728

In [ ]:
# Kis category me zyada discount diya ja raha hai
df.groupby('Category')['Discount'].mean().sort_values(ascending=False)

In [8]:
summary = (
    df.groupby(['Category','Sub-Category'])
      .agg({
          'Sales': 'sum',
          'Profit': 'sum',
          'Discount': 'mean'
      })
      .sort_values(by='Profit', ascending=False)
)

summary

                                    Sales      Profit  Discount
Category        Sub-Category
Technology      Copiers       149528.0300  55617.8249  0.161765
                Phones        330007.0540  44515.7306  0.154556
                Accessories   167380.3180  41936.6357  0.078452
Office Supplies Paper          78479.2060  34053.5693  0.074891
                Binders       203412.7330  30221.7633  0.372292
Furniture       Chairs        328449.1030  26590.1663  0.170178
Office Supplies Storage       223843.6080  21278.8264  0.074704
                Appliances    107532.1610  18138.0054  0.166524
Furniture       Furnishings    91705.1640  13059.1436  0.138349
Office Supplies Envelopes      16476.4020   6964.1767  0.080315
                Art            27118.7920   6527.7870  0.074874
                Labels         12486.3120   5546.2540  0.068681
Technology      Machines      189238.6310   3384.7569  0.306087
Office Supplies Fasteners       3024.2800    949.5182  0.082028
                Supplies       46673.5380  -1189.0995  0.076842
Furniture       Bookcases     114879.9963  -3472.5560  0.211140
                Tables        206965.5320 -17725.4811  0.261285

In [5]:
# Kaunsa sub-category overall profit de raha hai
df.groupby('Sub-Category')[['Sales','Profit']].sum().sort_values(by='Profit', ascending=False)

                    Sales      Profit
Sub-Category
Copiers       149528.0300  55617.8249
Phones        330007.0540  44515.7306
Accessories   167380.3180  41936.6357
Paper          78479.2060  34053.5693
Binders       203412.7330  30221.7633
Chairs        328449.1030  26590.1663
Storage       223843.6080  21278.8264
Appliances    107532.1610  18138.0054
Furnishings    91705.1640  13059.1436
Envelopes      16476.4020   6964.1767
Art            27118.7920   6527.7870
Labels         12486.3120   5546.2540
Machines      189238.6310   3384.7569
Fasteners       3024.2800    949.5182
Supplies       46673.5380  -1189.0995
Bookcases     114879.9963  -3472.5560
Tables        206965.5320 -17725.4811

In [6]:
df[df['Sub-Category'] == 'Chairs'][['Sales','Profit','Discount']].describe()

             Sales      Profit    Discount
count   617.000000  617.000000  617.000000
mean    532.332420   43.095894    0.170178
std     550.148243  127.099922    0.107444
min      26.640000 -630.882000    0.000000
25%     191.960000  -14.478400    0.100000
50%     362.136000   13.317600    0.200000
75%     662.880000   70.196000    0.300000
max    4416.174000  770.352000    0.300000

In [ ]:
# Q1. Top five products / categories contributing most to profit
summary.sort_values(by='Profit', ascending=False).head(5)

                                   Sales      Profit  Discount
Category        Sub-Category
Technology      Copiers       149528.030  55617.8249  0.161765
                Phones        330007.054  44515.7306  0.154556
                Accessories   167380.318  41936.6357  0.078452
Office Supplies Paper          78479.206  34053.5693  0.074891
                Binders       203412.733  30221.7633  0.372292

In [ ]:
# Q2. High sales but low / negative profit
loss = summary[(summary['Sales']>50000) & (summary['Profit']<0)]
loss

                              Sales      Profit  Discount
Category  Sub-Category
Furniture Bookcases     114879.9963  -3472.5560  0.211140
          Tables        206965.5320 -17725.4811  0.261285

In [ ]:
# Q3. Best performing region
df.groupby('Region')[['Sales','Profit']].sum().sort_values(by='Profit', ascending=False)

                             Profit
Region  Category
Central Furniture        -2871.0494
        Office Supplies   8879.9799
        Technology       33697.4320
East    Furniture         3046.1658
        Office Supplies  41014.5791
        Technology       47462.0351
South   Furniture         6771.2061
        Office Supplies  19986.3928
        Technology       19991.8314
West    Furniture        11504.9503
        Office Supplies  52609.8490
        Technology       44303.6496

In [13]:
df.groupby(['Region','Category'])[['Profit']].sum()

                             Profit
Region  Category
Central Furniture        -2871.0494
        Office Supplies   8879.9799
        Technology       33697.4320
East    Furniture         3046.1658
        Office Supplies  41014.5791
        Technology       47462.0351
South   Furniture         6771.2061
        Office Supplies  19986.3928
        Technology       19991.8314
West    Furniture        11504.9503
        Office Supplies  52609.8490
        Technology       44303.6496

In [ ]:
# Us region me kaunsi category zyada bikti hai?
df.groupby(['Region','Category'])[['Profit']].sum()